/*
 * src/riq/riq_play/scene/spacedance2p/spacedance2p_init.c
 *
 * Arcade game: spacedance
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
