/*
 * src/riq/riq_play/scene/iai/iai_init.c
 *
 * Arcade game: iai
 *
 * Decompilation pending — this is a stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
