/*
 * src/riq/riq_play/scene/marcherex2p/marcherex2p_init.c
 *
 * Arcade game: marcher
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
