/*
 * src/riq/riq_datacheck/init.c
 *
 * Subsystem: riq_datacheck
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
