/*
 * src/bomber/bomber_bsc.c
 *
 * Subsystem: bomber
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
