/*
 * src/riq/riq_play/scene/hair/hair_init.c
 *
 * Arcade game: hair
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
