/*
 * src/riq/riq_play/scene/rapman/init.c
 *
 * Arcade game: rapman
 *
 * Decompilation pending — this is a stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
