/*
 * src/riq/riq_play/scene/batterex2p/batterex2p_data.c
 *
 * Arcade game: batter
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
