/*
 * src/riq/riq_play/scene/drumosu/image.c
 *
 * Arcade game: drumosu
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
