/*
 * src/riq/riq_play/scene/boxingex2p/boxingex2p_init.c
 *
 * Arcade game: boxing
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
