/*
 * src/riq/riq_studio/bsd.c
 *
 * Subsystem: riq_studio
 *
 * Decompilation pending — stub generated by
 * tools/generate_game_dirs.py.  See ../README.md for status.
 */

#include "common.h"

/* (function bodies to be added as decompilation progresses) */
