#!/usr/bin/env python3
"""
tools/parse_beatscript_v2.py

Re-parses BeatScript bytecode using the FULL opcode table imported
from the GBA RT decomp.

Major changes vs v1:
  * Opcodes 0x00 (rest) and 0x01 (stop) recognised as valid (v1 treated
    them as padding/sentinel).
  * Per-opcode pretty-printing using GBA macro names.
  * Walk forward from any opcode 0x00-0xB2 (with appropriate padding
    constraints) — much more permissive boundary detection.
  * For each unique region, emit annotated disassembly.

The GBA opcode table is loaded from build/gba_beatscript_opcodes.json
(generated by parsing /Users/sumirintarou/rt/include/beatscript_main.inc).

Outputs:
  build/beatscripts_v2/regions.txt
  build/beatscripts_v2/scripts/<addr>.bs.txt
  build/beatscripts_v2/opcode_stats.md
"""

import json
import struct
from pathlib import Path
from collections import defaultdict, Counter

ROOT     = Path('/Users/sumirintarou/rhytngk-arcade-decomp')
ROM_PATH = ROOT / 'roms/fpr-24423_decrypted.bin'
OPS_JSON = ROOT / 'build/gba_beatscript_opcodes.json'
OUT_DIR  = ROOT / 'build/beatscripts_v2'
VRAM     = 0x0c000000


def load_opcodes():
    with open(OPS_JSON) as f:
        raw = json.load(f)
    return {int(k, 16): v for k, v in raw.items()}


def opcode_arg_kind(op):
    """
    Returns 'sub' if opcode uses sub-op in byte 1 (op 0x04, 0x05-0x0C,
    0xAC-0xAE, 0xB2 etc.), else 'none'.
    """
    # From the GBA macro definitions, ops with a non-zero arg1 byte:
    if op == 0x04: return 'sub'        # run2 (arg1 = arg1)
    if op in range(0x05, 0x0D): return 'sub'  # set_var/add_var/set_bit/etc. type
    if op == 0x21 or op == 0x22: return 'sub'  # scene_if (type)
    if op in (0xAC, 0xAD): return 'sub'  # set_music_track_volume etc.
    if op == 0xAE: return 'sub'        # play_sfx_vol_pitch (volume in arg1)
    if op == 0xB2: return 'sub'
    return 'none'


def is_valid_instr(rom, off, ops):
    """Strict validation: opcode must be known AND padding bytes must be zero."""
    if off + 12 > len(rom): return False
    op = rom[off]
    if op not in ops: return False
    b1, b2, b3 = rom[off+1], rom[off+2], rom[off+3]
    kind = opcode_arg_kind(op)
    if kind == 'none':
        return (b1, b2, b3) == (0, 0, 0)
    if kind == 'sub':
        return (b2, b3) == (0, 0)
    return False


def parse_script(rom, start, ops, max_len=1000):
    insns = []
    off = start
    while off + 12 <= len(rom) and len(insns) < max_len:
        if not is_valid_instr(rom, off, ops): break
        op = rom[off]
        sub = rom[off+1]
        arg2 = struct.unpack_from('<I', rom, off+4)[0]
        arg3 = struct.unpack_from('<I', rom, off+8)[0]
        insns.append({'off': off, 'op': op, 'sub': sub, 'arg2': arg2, 'arg3': arg3})
        off += 12
        # Stop on 0x01 (stop), 0x0E (return), 0x0F (goto)
        if op in (0x01, 0x0E, 0x0F): break
    return insns


def find_unique_regions(rom, ops, min_len=8):
    visited = set()
    regions = []
    for off in range(0, len(rom) - 12, 4):
        if off in visited: continue
        if not is_valid_instr(rom, off, ops): continue
        insns = parse_script(rom, off, ops)
        if len(insns) >= min_len:
            # Check no instruction has already been visited; if so, skip
            already = any(i['off'] in visited for i in insns)
            if already: continue
            regions.append({'start': off, 'insns': insns})
            for i in insns:
                visited.add(i['off'])
    return regions


def format_instr(ins, ops):
    op = ins['op']
    info = ops.get(op, {'description': '?', 'macro': None})
    macro = info['macro'] or f'op_{op:02x}'
    desc = info['description']
    parts = []
    if ins['sub'] != 0:
        parts.append(f'sub=0x{ins["sub"]:02x}')
    parts.append(f'arg2=0x{ins["arg2"]:08x}')
    parts.append(f'arg3=0x{ins["arg3"]:08x}')
    return f'{macro:24s} {" ".join(parts):60s}  // {desc}'


def main():
    rom = ROM_PATH.read_bytes()
    ops = load_opcodes()
    print(f"Loaded {len(ops)} GBA opcode definitions")
    print(f"Scanning {len(rom):,} bytes of ROM...")

    regions = find_unique_regions(rom, ops, min_len=8)
    print(f"Found {len(regions)} unique regions (>= 8 instructions)")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    scripts_dir = OUT_DIR / 'scripts'
    scripts_dir.mkdir(exist_ok=True)

    # Summary
    summary = ['# BeatScript Regions v2 (with GBA opcode names)',
               f'# ROM: {ROM_PATH.name}',
               f'# Opcode dict: {OPS_JSON.relative_to(ROOT)}',
               f'# Total distinct regions: {len(regions)}',
               '',
               '| Start VRAM | Length | File |',
               '|---|---|---|']

    op_stats = Counter()
    fn_stats = Counter()  # for op 0x03/0x04 callees

    for r in sorted(regions, key=lambda x: -len(x['insns'])):
        addr = VRAM + r['start']
        fname = f'script_{addr:08x}.bs.txt'
        out = scripts_dir / fname
        lines = [f'# BeatScript region @ 0x{addr:08x}',
                 f'# Length: {len(r["insns"])} instructions ({len(r["insns"])*12} bytes)',
                 '']
        for ins in r['insns']:
            ia = VRAM + ins['off']
            lines.append(f'  0x{ia:08x}  {format_instr(ins, ops)}')
            op_stats[ins['op']] += 1
            if ins['op'] in (0x03, 0x04, 0x02, 0x0D):
                fn_stats[ins['arg2']] += 1
        out.write_text('\n'.join(lines) + '\n')
        summary.append(f'| 0x{addr:08x} | {len(r["insns"])} | scripts/{fname} |')

    (OUT_DIR / 'regions.txt').write_text('\n'.join(summary) + '\n')

    # Opcode stats
    rep = ['# BeatScript Opcode Usage Statistics',
           f'# Across {len(regions)} regions, total {sum(op_stats.values())} instructions',
           '',
           '| Opcode | Count | Macro | Description |',
           '|---|---|---|---|']
    for op in sorted(op_stats, key=lambda x: -op_stats[x]):
        info = ops.get(op, {'description': '?', 'macro': '?'})
        rep.append(f'| 0x{op:02X} | {op_stats[op]} | {info["macro"]} | {info["description"]} |')
    (OUT_DIR / 'opcode_stats.md').write_text('\n'.join(rep) + '\n')

    # Top function pointers
    print(f"\nTop 15 opcodes:")
    for op, cnt in op_stats.most_common(15):
        info = ops.get(op, {'description': '?', 'macro': '?'})
        print(f"  0x{op:02X} ({info['macro'] or '?':20s}): {cnt:5d}  ({info['description']})")

    print(f"\nTop 10 function pointers called by run/run2/scene_run/call:")
    for fn, cnt in fn_stats.most_common(10):
        print(f"  0x{fn:08x}: {cnt}")

    print(f"\nWrote {len(regions)} scripts to {scripts_dir}")


if __name__ == '__main__':
    main()
