/*
 * code_0c020140.c — TU 2/5 of the EstexNT-verified window.
 *   covers func_0c020140 .. func_0c021174   (37 functions)
 *   [0x0C020140, 0x0C021250)
 *
 * Function boundaries: [verified] (EstexNT ground truth,
 * tools/ground_truth_estex.txt).  Bodies: hand-translated from
 * tools/sh4_disasm.py output with literal pools resolved from
 * roms/fpr-24423_decrypted.bin, then byte-compared against the ROM by
 * `make status` — run it for this TU's current state rather than trusting
 * a count written here.  Functions that cannot yet be expressed
 * faithfully in C carry an INCLUDE_ASM placeholder instead (EstexNT
 * convention) — an honest placeholder beats wrong C.
 *
 * This binary was compiled as C++ with exceptions: several functions
 * contain compiler-generated EH landing pads (unreachable blocks that
 * record state and call the unwind helper at 0x0C129EE0).  Where a
 * function's only C++-ism is such pads, the body is written as plain C
 * and the pads are noted — they would be regenerated by a C++ compiler.
 *
 * Roles for the spine functions are established in docs/boot_and_main.md
 * and docs/frame_pipeline_stages.md.  CORRECTIONS to those docs found
 * while translating (flagged, not silently diverged):
 *   1. docs/frame_pipeline_stages.md lists stage 5 (frame_stage5_update)
 *      calling func_0c03099c twice.  The pool at 0x0C0204C4 reads
 *      0x0C02039C: the 5th call is the in-window func_0c02039c (once),
 *      and func_0c03099c runs once (pool 0x0C0204D8).
 *   2. The same doc describes stage 6 (frame_stage6_update) as looping over a
 *      runtime-sized list.  There is no loop: the "body at 0x020792" is
 *      an unreachable EH landing pad.  The function is a straight-line
 *      update group instrumented with tick counters (see below).
 */

#include "rt_types.h"

/* ---------------- extern call targets (addresses [verified] from
 * literal pools; signatures inferred from observed argument setup) --- */

/* shared no-op debug/trace hook — empty body in retail
 * (docs/frame_pipeline_stages.md) */
extern void func_0c032662(u8 *marker);

/* static-init helpers reached from func_0c020140/func_0c0201a0.
 * Tested-before-call through literal-pool addresses (weak-reference
 * pattern). */
extern void func_0c12ae40(void *);
extern void func_0c12a1a0(void *, void *);

/* func_0c020200 handler targets */
extern void func_0c030b28(void *);
extern void func_0c0386cc(void *);
extern void func_0c038f5c(void *);
extern void func_0c031108(void *);

/* teardown (func_0c0202b0) targets */
extern void func_0c03b3d4(void *);
extern void func_0c038628(void);
extern void func_0c03eaa0(void);
extern void func_0c0309c4(void);
extern void func_0c037e70(void);
extern void func_0c0ebd4c(void);

/* stage-sync (frame_stage8_sync) */
extern s32  func_0c0f1a90(void);      /* free-running counter/timer read */
extern void func_0c0f1634(void *);

/* func_0c02039c chain */
extern s32  func_0c034fcc(s32);
extern s32  func_0c0354f4(s32, s32);
extern s32  func_0c03655e(void);
extern s32  func_0c03c638(void);
extern s32  func_0c0365f6(void);
extern void func_0c040fa0(s32);
extern void func_0c0368ac(void);
extern void func_0c037a78(void);

/* stage 5 (frame_stage5_update) targets */
extern void func_0c037db8(void);
extern void func_0c037ea0(void);
extern void func_0c037ed0(void);
extern void func_0c03eabc(void);
extern void func_0c038b38(void);
extern void func_0c066a08(void);
extern void func_0c06624c(void);
extern void func_0c03099c(void);
extern void func_0c03a520(void *);
extern void func_0c037ccc(void);

/* init4 (func_0c0204e8) targets */
extern void func_0c0f8ef4(void);
extern void func_0c0ecf3c(void);
extern u32 *func_0c0ec550(void);
extern void func_0c0f3388(s32, s32, s32);
extern void func_0c0f8ec8(void);
extern void func_0c0e799c(void);
extern void func_0c0e7664(s32, s32 (*fn)(void));  /* callback registration */
extern void func_0c0f2e7c(void);
extern void func_0c0f175c(u32);
extern void func_0c0f17d8(u32);
extern void func_0c0f2938(s32, s32, u32, s32);
extern void func_0c0f33a4(void);
extern void func_0c0f5b1c(void *, s32);
extern void func_0c0f08b4(void *, s32, s32);
extern void func_0c0e591c(void *, s32, s32);
extern void func_0c0f110c(void *, s32);
extern void func_0c0f135c(s32);
extern void func_0c0f1348(s32);
extern void func_0c0dfbe4(void);
extern void func_0c0eb63c(s32, s32);
extern void func_0c0f3fd8(void *);
extern void func_0c0f44f0(void);
extern void func_0c0f4220(void);
extern void func_0c0f4254(s32, s32);
extern void func_0c03e730(void);
extern void func_0c037218(void);
extern void func_0c030730(void);
extern void func_0c03c1c8(void *);
extern void func_0c03511c(void);
extern void func_0c03e97c(s32, s32);
extern void func_0c0380a8(void);
extern void func_0c02ec38(void);
extern void func_0c03c86c(void);
extern void func_0c039424(void);

/* frame-sync flag setter callback (func_0c0206fc) */
extern void func_0c0f1388(void);

/* func_0c020724 targets */
extern void func_0c036718(void);
extern void func_0c02f3c4(void);

/* stage 6 (frame_stage6_update) targets */
extern void func_0c037d94(void);
extern s32  func_0c037d00(void);      /* read tick/counter */
extern u32  func_0c037ca8(s32);       /* elapsed since tick */
extern void func_0c038a58(void);
extern void func_0c0389e4(void);
extern void func_0c066294(void);
extern void func_0c066358(void);
extern void func_0c062b78(s32);
extern void func_0c037d1c(void);

/* frame pipeline (frame) targets */
extern void func_0c0f2164(void);
extern void func_0c03c652(void);
extern void func_0c0f1a70(void);
extern void func_0c0f1608(void);
extern void func_0c0ef608(void);
extern void func_0c0f1ac8(void);

/* main (func_0c020c08) targets */
extern void func_0c037f00(void);      /* init 2 [scanner boundary] */
extern void func_0c03c4cc(s32);       /* init 3 [scanner boundary] */
extern s32  is_quit_requested(void);  /* 0x0C037A90; reads *(u8*)0x0C4655F8 */

/* interrupt-mask bracketing used by init4:
 *   raise: sr = (sr & 0xFFFFFF0F) | 0xE0   (IMASK = 14)
 *   lower: sr =  sr & 0xFFFFFF0F           (IMASK = 0)
 * Requires privileged inline asm on a real build.                     */
#ifdef __GNUC__
static inline void irq_mask_raise(void)
{
    u32 sr;
    __asm__ volatile("stc sr,%0" : "=r"(sr));
    sr = (sr & 0xFFFFFF0F) | 0xE0;
    __asm__ volatile("ldc %0,sr" : : "r"(sr));
}
static inline void irq_mask_lower(void)
{
    u32 sr;
    __asm__ volatile("stc sr,%0" : "=r"(sr));
    sr = sr & 0xFFFFFF0F;
    __asm__ volatile("ldc %0,sr" : : "r"(sr));
}
#else
void irq_mask_raise(void);
void irq_mask_lower(void);
#endif

/* forward decls for in-window functions used before definition */
void func_0c020200(s32 mode, s32 key);
void func_0c02039c(void);
s32  func_0c0206fc(void);
s32  func_0c020724(void);
void frame_stage5_update(void);
void frame_stage6_update(void);
void frame_stage8_sync(void);
void func_0c02095c(s32 boot_mode, void *boot_ptr); /* INCLUDE_ASM below */
void func_0c020d64(s32 mode, s32 key);             /* INCLUDE_ASM below */
void func_0c020f30(s32 mode, s32 key);
void func_0c0204e8(void);
void frame(void);
void func_0c02028c(void);
void func_0c0202b0(void);

/* ================================================================== */
/* func_0c020140 @ 0x0C020140, size 0x60 — run static initializers    */
/* once.  Walks the 0-terminated function-pointer table whose cursor  */
/* lives at 0x0C2B1B04 (advancing the cursor before each call), then  */
/* invokes the weak hook func_0c12ae40(0x0C2779FC) if linked.         */
/* confidence: high (small, fully traced)                             */
/* ================================================================== */
void func_0c020140(void)
{
    u32 *cursor;
    void (*fn)(void);

    if (g_static_init_done == 0) {
        cursor = g_ctor_cursor;
        fn = (void (*)(void))*cursor;
        while (fn != NULL) {
            g_ctor_cursor = cursor + 1;
            fn();
            cursor = g_ctor_cursor;
            fn = (void (*)(void))*cursor;
        }
        /* weak-reference pattern: pool holds the callee address and the
         * code tests it for 0 before calling */
        if (func_0c12ae40 != NULL) {
            func_0c12ae40((void *)0x0C2779FC);
        }
        g_static_init_done = 1;
    }
}

/* ================================================================== */
/* func_0c0201a0 @ 0x0C0201A0, size 0x60 — static-init companion.     */
/* Calls weak func_0c12a1a0(0x0C2779FC, 0x0C431E1C) if linked, then   */
/* would tail-jump a handler if *(u32*)0x0C2B1AE0 != 0 — but the      */
/* handler slot in this build's pool (0x0C0201FC) is NULL, so the     */
/* jump can never be taken.                                           */
/* confidence: high                                                   */
/* ================================================================== */
void func_0c0201a0(void)
{
    void (*handler)(void) = NULL;   /* pool @0x0C0201FC = 0x00000000 */

    if (func_0c12a1a0 != NULL) {
        func_0c12a1a0((void *)0x0C2779FC, (void *)0x0C431E1C);
    }
    if (g_unk_0C2B1AE0 != 0 && handler != NULL) {
        handler();                  /* emitted as tail jmp @r2 */
        return;
    }
}

/* ================================================================== */
/* func_0c020200 @ 0x0C020200, size 0x68 — mode 0/1 handler pair      */
/* operating on the byte globals 0x0C461C5C / 0x0C461C5D.  Registered */
/* through the (mode, key=0xFFFF) convention used by the wrappers     */
/* below.  confidence: high                                           */
/* ================================================================== */
void func_0c020200(s32 mode, s32 key)
{
    if (mode == 1) {
        if (key == 0xFFFF) {
            func_0c030b28((void *)0x0C461C5C);
            func_0c0386cc((void *)0x0C461C5D);
        }
    } else if (mode == 0 && key == 0xFFFF) {
        func_0c038f5c((void *)0x0C461C5D);
        func_0c031108((void *)0x0C461C5C);
    }
}

/* func_0c020268 @ 0x0C020268, size 0x24 — wrapper: mode-0 entry.     */
void func_0c020268(void)
{
    func_0c020200(0, 0xFFFF);
}

/* func_0c02028c @ 0x0C02028C, size 0x24 — wrapper: mode-1 entry.     */
void func_0c02028c(void)
{
    func_0c020200(1, 0xFFFF);
}

/* ================================================================== */
/* func_0c0202b0 @ 0x0C0202B0, size 0x54 — engine teardown, called by */
/* main after the loop exits (docs/boot_and_main.md).                 */
/* confidence: high (straight-line)                                   */
/* ================================================================== */
void func_0c0202b0(void)
{
    func_0c03b3d4((void *)0x0C4669D8);
    func_0c038628();
    func_0c03eaa0();
    func_0c0309c4();
    func_0c037e70();
    func_0c0ebd4c();
}

/* ================================================================== */
/* frame_stage8_sync @ 0x0C020304, size 0x98 — frame pipeline stage 8:    */
/* bounded spin-wait on the frame-sync flag (set from the callback    */
/* func_0c0206fc), then clear it and notify func_0c0f1634.            */
/* docs/frame_pipeline_stages.md ("stage_sync").                      */
/* confidence: high                                                   */
/* ================================================================== */
void frame_stage8_sync(void)
{
    u8 m[2][4];                 /* debug markers passed to the no-op hook */

    m[0][0] = 63; m[0][1] = 63; m[0][2] = 63; m[0][3] = 0xFF;
    func_0c032662(m[0]);

    while (g_frame_sync_flag == 0) {
        if (func_0c0f1a90() > 16000) {  /* pool word @0x0C020384 = 0x3E80 */
            break;
        }
    }
    g_frame_sync_flag = 0;
    func_0c0f1634(g_frame_sync_obj);

    m[1][0] = 0; m[1][1] = 0; m[1][2] = 0; m[1][3] = 0xFF;
    func_0c032662(m[1]);
}

/* ================================================================== */
/* func_0c02039c @ 0x0C02039C, size 0xA4 — conditional dispatcher     */
/* called from stage 5.  Queries func_0c034fcc(0), probes it with     */
/* func_0c0354f4(t,0) / (t,17), then branches between three actions.  */
/* (The original keeps t alive across calls in fr12 — callee-saved    */
/* float register used as an integer save slot.)                      */
/* confidence: high on control flow; callee roles unknown             */
/* ================================================================== */
void func_0c02039c(void)
{
    s32 t;

    t = func_0c034fcc(0);
    if (func_0c0354f4(t, 0) != 0 || func_0c0354f4(t, 17) != 0) {
        if (func_0c03655e() == 0 && func_0c03c638() == 0) {
            func_0c037a78();
            return;
        }
    }
    if (func_0c0365f6() == 0) {
        func_0c040fa0(15);
    } else if (func_0c03655e() == 0) {
        func_0c0368ac();
    }
}

/* ================================================================== */
/* frame_stage5_update @ 0x0C020440, size 0xA8 — frame pipeline stage 5:    */
/* flat update group, 12 calls in fixed order.                        */
/* NOTE: corrects docs/frame_pipeline_stages.md — the 5th call is the */
/* in-window func_0c02039c (pool 0x0C0204C4 = 0x0C02039C), not a      */
/* second func_0c03099c.                                              */
/* confidence: high (straight-line)                                   */
/* ================================================================== */
void frame_stage5_update(void)
{
    u8 m[4];

    func_0c037db8();
    m[0] = 0; m[1] = 0xFF; m[2] = 0; m[3] = 0xFF;
    func_0c032662(m);
    func_0c037ea0();
    func_0c037ed0();
    func_0c02039c();
    func_0c03eabc();
    func_0c038b38();
    func_0c066a08();
    func_0c06624c();
    func_0c03099c();
    func_0c03a520((void *)0x0C4669D8);
    func_0c037ccc();
}

/* ================================================================== */
/* func_0c0204e8 @ 0x0C0204E8, size 0x214 — init 4: master subsystem  */
/* init called from main (docs/boot_and_main.md).  Two groups are     */
/* bracketed with interrupt-mask raises; then ~24 further inits run   */
/* with interrupts enabled.  All constants read from the pool.        */
/* confidence: high (straight-line; one probed field selects 9 vs 0)  */
/* ================================================================== */
void func_0c0204e8(void)
{
    u32 *p;
    s32 arg;

    irq_mask_raise();
    func_0c0f8ef4();
    func_0c0ecf3c();
    p = func_0c0ec550();
    arg = (p[3] == 0) ? 9 : 0;          /* @(12,r0) probed */
    func_0c0f3388(arg, 128, 1);
    irq_mask_lower();

    irq_mask_raise();
    func_0c0f8ec8();
    func_0c0e799c();
    func_0c0e7664(1, func_0c020724);    /* register callback, slot 1 */
    func_0c0e7664(0, func_0c0206fc);    /* register callback, slot 0 */
    irq_mask_lower();

    func_0c0f2e7c();
    func_0c0f175c(0x00340000);
    func_0c0f17d8(0x0DF00000);
    func_0c0f2938(0, 0, 0x00030000, 0);
    func_0c0f33a4();
    func_0c0f5b1c((void *)0x0C431E9C, 32);
    func_0c0f08b4((void *)0x0C43269C, 2048, 4096);
    func_0c0e591c((void *)0x0C4589DC, 1024, 2048);
    func_0c0f110c((void *)0x0C461A5C, 64);
    func_0c0f135c(0);
    func_0c0f1348(1);
    func_0c0dfbe4();
    func_0c0eb63c(2, 0);
    func_0c0f3fd8((void *)0x0C1BFA70);
    func_0c0f44f0();
    func_0c0f4220();
    func_0c0f4254(8, 8);
    func_0c03e730();
    func_0c037218();
    func_0c030730();
    func_0c03c1c8((void *)0x0C4669D8);
    func_0c03511c();
    func_0c03e97c(-1, -1);
    func_0c0380a8();
    func_0c02ec38();
    func_0c03c86c();
    func_0c039424();
}

/* ================================================================== */
/* func_0c0206fc @ 0x0C0206FC, size 0x28 — callback registered via    */
/* func_0c0e7664(0, ...): sets the frame-sync flag consumed by stage  */
/* frame_stage8_sync (VBlank-ish notification), then func_0c0f1388().     */
/* confidence: high                                                   */
/* ================================================================== */
s32 func_0c0206fc(void)
{
    g_frame_sync_flag = 1;
    func_0c0f1388();
    return 0;
}

/* ================================================================== */
/* func_0c020724 @ 0x0C020724, size 0x28 — callback registered via    */
/* func_0c0e7664(1, ...).  confidence: high                           */
/* ================================================================== */
s32 func_0c020724(void)
{
    func_0c036718();
    func_0c02f3c4();
    return 0;
}

/* ================================================================== */
/* frame_stage6_update @ 0x0C02074C, size 0x1A4 — frame pipeline stage 6:   */
/* straight-line update group instrumented with tick counters: three  */
/* sub-groups are timed with func_0c037d00() (tick read) and          */
/* func_0c037ca8(tick) (elapsed), results stored to the globals       */
/* 0x0C431E4C/50/54.                                                  */
/* NOTE: corrects docs/frame_pipeline_stages.md — the "loop body at   */
/* 0x020792" is an unreachable EH landing pad (records elapsed time,  */
/* then resumes unwinding via 0x0C129EE0); there is no iteration.     */
/* confidence: high (straight-line once pads are excluded)            */
/* ================================================================== */
void frame_stage6_update(void)
{
    u8 m[5][4];
    s32 tick;

    m[0][0] = 0xFF; m[0][1] = 0; m[0][2] = 0; m[0][3] = 0xFF;
    func_0c032662(m[0]);

    func_0c037d94();
    tick = func_0c037d00();
    func_0c038a58();
    func_0c0389e4();
    g_frame_time_a = func_0c037ca8(tick);

    m[1][0] = 0xFF; m[1][1] = 0xFF; m[1][2] = 0xFF; m[1][3] = 0xFF;
    func_0c032662(m[1]);
    m[2][0] = 0; m[2][1] = 0xFF; m[2][2] = 0xFF; m[2][3] = 0xFF;
    func_0c032662(m[2]);

    tick = func_0c037d00();
    func_0c066294();
    func_0c066358();
    func_0c066a08();
    g_frame_time_b = func_0c037ca8(tick);

    m[3][0] = 0xFF; m[3][1] = 0; m[3][2] = 0xFF; m[3][3] = 0xFF;
    func_0c032662(m[3]);

    tick = func_0c037d00();
    func_0c062b78(0);
    g_frame_time_c = func_0c037ca8(tick);
    func_0c037d1c();

    m[4][0] = 0; m[4][1] = 0; m[4][2] = 0; m[4][3] = 0xFF;
    func_0c032662(m[4]);
}

/* ================================================================== */
/* frame @ 0x0C0208F0, size 0x6C — per-frame body: the 9-stage*/
/* pipeline, called from main's loop (docs/boot_and_main.md).         */
/* confidence: high (straight-line, matches docs)                     */
/* ================================================================== */
void frame(void)
{
    func_0c0f2164();
    func_0c03c652();
    func_0c0f1a70();
    func_0c0f1608();
    frame_stage5_update();
    frame_stage6_update();
    func_0c0ef608();
    frame_stage8_sync();
    func_0c0f1ac8();
}

/* ================================================================== */
/* func_0c02095c @ 0x0C02095C, size 0x2AC — init 1: boot-argument /   */
/* configuration parser, run as func_0c02095c(boot_mode, boot_ptr)    */
/* (inherits main's live r4/r5 — docs/boot_and_main.md).              */
/* NOT yet expressed in C: the body is C++ using refcounted string    */
/* objects (empty-string rep 0x0C571988, atomic refcount helper       */
/* 0x0C118DC0, destructor 0x0C1A1A40, string ctor 0x0C1A31C0, dtor    */
/* paths via 0x0C129EE0) and multiple EH landing pads.  Faithful C is */
/* not possible without fabricating the string class; keeping asm.    */
/* ================================================================== */
// INCLUDE_ASM("asm/code_0c020140/func_0c02095c")

/* ================================================================== */
/* main @ 0x0C020C08, size 0x6C — named in symbols.txt [T].          */
/* NOTE: r4/r5 are not reloaded before the func_0c02095c call, so     */
/* init 1 observes main's own arguments.                              */
/* ================================================================== */
s32 main(s32 boot_mode, void *boot_ptr)
{
    func_0c02095c(boot_mode, boot_ptr);  /* init 1 (in-window) */
    func_0c037f00();                     /* init 2 [scanner]   */
    func_0c03c4cc(1);                    /* init 3 [scanner]   */
    func_0c0204e8();                     /* init 4 (in-window) */

    while (is_quit_requested() == 0) {   /* while (!*(u8*)0x0C4655F8) */
        frame();                 /* one frame */
    }

    func_0c0202b0();                     /* teardown */
    return 0;
}

/* ------- tiny stub family @ 0x0C020C74..0x0C020CB6 (retail no-ops,  */
/* return-0 vs void variants preserved exactly) --------------------- */

/* func_0c020c74 @ 0x0C020C74, size 0x0E */
s32 func_0c020c74(void) { return 0; }

/* func_0c020c82 @ 0x0C020C82, size 0x0C */
void func_0c020c82(void) {}

/* func_0c020c8e @ 0x0C020C8E, size 0x0C */
void func_0c020c8e(void) {}

/* func_0c020c9a @ 0x0C020C9A, size 0x0E */
s32 func_0c020c9a(void) { return 0; }

/* func_0c020ca8 @ 0x0C020CA8, size 0x0E */
s32 func_0c020ca8(void) { return 0; }

/* func_0c020cb6 @ 0x0C020CB6, size 0x0C */
void func_0c020cb6(void) {}

/* ------- global setter family @ 0x0C020CC4..0x0C020D34 ------------ */
/* (int/float pairs at 0x0C461C68/6C, float quad at 0x0C461C70..7C)   */

/* func_0c020cc4 @ 0x0C020CC4, size 0x18 */
s32 func_0c020cc4(s32 x)
{
    g_unk_0C461C68 = x;
    return x;
}

/* func_0c020cdc @ 0x0C020CDC, size 0x18 */
f32 func_0c020cdc(f32 x)
{
    g_unk_0C461C6C = x;
    return x;
}

/* func_0c020cf4 @ 0x0C020CF4, size 0x20 — int stored first.
 * (int arg in r4, float arg in fr4; declaration order of the two
 * parameters is not recoverable from codegen) */
f32 func_0c020cf4(s32 a, f32 b)
{
    g_unk_0C461C68 = a;
    g_unk_0C461C6C = b;
    return b;
}

/* func_0c020d14 @ 0x0C020D14, size 0x20 — float stored first. */
f32 func_0c020d14(s32 a, f32 b)
{
    g_unk_0C461C6C = b;
    g_unk_0C461C68 = a;
    return b;
}

/* func_0c020d34 @ 0x0C020D34, size 0x30 */
f32 func_0c020d34(f32 a, f32 b, f32 c, f32 d)
{
    g_unk_0C461C70 = a;
    g_unk_0C461C74 = b;
    g_unk_0C461C78 = c;
    g_unk_0C461C7C = d;
    return a;
}

/* ================================================================== */
/* func_0c020d64 @ 0x0C020D64, size 0x184 — (mode, key) handler.      */
/* mode==1: sets *(void**)0x0C461C64 = 0x0C24E9F4 and builds a set of */
/* stack-allocated registration records via 0x0C12D340 / 0x0C12D920 / */
/* 0x0C12DB5C / 0x0C12CBBC (5+ args passed on stack); mode==0: sets   */
/* *(void**)0x0C461C64 = 0x0C24EAA0.  NOT yet expressed in C: the     */
/* record types/ctors are unresolved and the stack layout is C++      */
/* object construction — faithful C would require fabricating them.   */
/* ================================================================== */
// INCLUDE_ASM("asm/code_0c020140/func_0c020d64")

/* func_0c020ee8 @ 0x0C020EE8, size 0x24 — wrapper: mode-0 entry.     */
void func_0c020ee8(void)
{
    func_0c020d64(0, 0xFFFF);
}

/* func_0c020f0c @ 0x0C020F0C, size 0x24 — wrapper: mode-1 entry.     */
void func_0c020f0c(void)
{
    func_0c020d64(1, 0xFFFF);
}

/* func_0c020f30 @ 0x0C020F30, size 0x0C — empty (mode,key) handler.  */
void func_0c020f30(s32 mode, s32 key) {}

/* func_0c020f3c @ 0x0C020F3C, size 0x24 — wrapper: mode-1 entry of   */
/* the empty handler above.                                           */
void func_0c020f3c(void)
{
    func_0c020f30(1, 0xFFFF);
}

/* func_0c020f60 @ 0x0C020F60, size 0x0C */
void func_0c020f60(void) {}

/* func_0c020f6c @ 0x0C020F6C, size 0x0C */
void func_0c020f6c(void) {}

/* ================================================================== */
/* func_0c020f78 @ 0x0C020F78, size 0xD0 — C++: returns a refcounted  */
/* string object through the hidden aggregate-return pointer (r2).    */
/* Searches for '.' from a table at 0x0C24EAAC via 0x0C1A2240         */
/* (find_last_of-like), substrings via 0x0C1A3840, bounds-checks via  */
/* 0x0C111220(0x0C24EAB4 = throw site).  Keeping asm; EH pads present.*/
/* ================================================================== */
// INCLUDE_ASM("asm/code_0c020140/func_0c020f78")

/* ================================================================== */
/* func_0c021048 @ 0x0C021048, size 0x12C — C++ string helper (hidden */
/* r2 aggregate return; find via 0x0C1A2240 table 0x0C24EACC, copy    */
/* via 0x0C1A3840 / 0x0C1A4A80).  Keeping asm; EH pads present.       */
/* ================================================================== */
// INCLUDE_ASM("asm/code_0c020140/func_0c021048")

/* ================================================================== */
/* func_0c021174 @ 0x0C021174, size 0xDC — C++ string helper (hidden  */
/* r2 aggregate return; same helper set as func_0c021048).            */
/* Keeping asm; EH pads present.                                      */
/* ================================================================== */
// INCLUDE_ASM("asm/code_0c020140/func_0c021174")
